# Generated by Django 4.0.6 on 2022-07-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
