# Generated by Django 4.1.6 on 2023-02-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
